# Project-wide Gradle settings.

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36

# JVM settings
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m

# Kotlin
kotlin.suppressKotlinVersionCompatibilityCheck=true

# Gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true

# Android Studio
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.resvalues=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Enable Jetpack Compose
android.enableJetpackCompose=true